name: Daily oil import

on:
  schedule:
    - cron: '45 15 * * *'

jobs:
  populate-database:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy
        pip install requests
        pip install pyodbc
        pip install pyyaml
        pip install pandas

    - name: Run the script
      working-directory: ./azure
      run: python oil_companies_import.py
