name: Daily oil import

on:
  schedule:
    - cron: '50 14 * * *'  # Scheduled to run at 14:50 UTC every day

jobs:
  populate-database:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy
        pip install requests
        pip install pyodbc
        pip install pyyaml

    - name: Change to the azure directory
      run: cd azure
      
    - name: Run the script
      run: python oil_companies_import.py

      



